### ISSUE TITLE
Application silently crashes to Desktop

### ISSUE THREAD

**Issue by TheNastyCapivara** [Pathoschild/SMAPI#260]
I don't know if this is an issue with Stardew Valley or SMAPI, but given I wasn't experiencing it before installing SMAPI I'm guessing it's something with it or the mods I'm using. The problem I have is that the game just randomly closes after a while playing with the logs not giving any information regarding as to why. The application just exits for no reason. I'm attaching the log but as you can see there is no error message or anything of the kind.

Here is the log:
[SMAPI-latest.txt](https://github.com/Pathoschild/SMAPI/files/945694/SMAPI-latest.txt)

**Comment by Pathoschild** [comment]
@TheNastyCapivara: That's probably not related to SMAPI or the mods you have installed, since their errors are intercepted and shown in the console. The crash may be happening in unmanaged audio or video code (i.e. your graphics/audio drivers or hardware), which would explain why there's no error in the log. I can't help much with those, unfortunately.
