### ISSUE TITLE
SMAPI error

### ISSUE THREAD

**Issue by caerolx3** [Pathoschild/SMAPI#313]
Hi,
I have the most recent SMAPI 1.14.1 installed and it has been working perfectly fine up until today. When trying to open the game it suddenly stopped working with this displayed "Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'StardewModdingAPI.AssemblyRewriters, Version=1.14.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at StardewModdingAPI.Program.Main(String[] args)".
How do I fix this?
Thanks

**Comment by Pathoschild** [comment]
Hi @caerolx3. It looks like one of the SMAPI files (specifically <code>StardewModdingAPI.AssemblyRewriters.dll</code>) is missing from the game folder, probably because you have an antivirus that's removing it. See [this FAQs entry for info](http://stardewvalleywiki.com/Modding:Player_FAQs#StardewModdingAPI.exe_disappears_or_your_antivirus_complains).

If you need any other help, feel free to post a message in [the SMAPI support thread](http://community.playstarbound.com/threads/108375). :)
