### ISSUE TITLE
SMAPI won't run.  "Unhandled exception" error

### ISSUE THREAD

**Issue by GirlGalvanized** [Pathoschild/SMAPI#365]
Edit: FIXED!!  My fiance got on the discord and was able to get awesome help from Pathoschild immediately!  For anyone else who might find this: Turns out Norton was removing a necessary file, so I made my StardewValley folder an exception in Norton, temporarily disabled Norton, and then re-downloaded SMAPI (in case the anti-virus had removed the file from the download), reinstalled SMAPI, and everything worked perfectly!  Thank you so much!!  

Hello!  I'm sorry.  I've tried to solve this on my own and I just can't figure it out.  I installed SMAPI today and tried to run it without adding any mods yet just to make sure it was okay, but it won't open at all.  This is the error I'm getting:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'StardewModdingAPI.AssemblyRewriters, Version=1.15.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at StardewModdingAPI.Program.Main(String[] args)

I've found other users with a similar error, but I just can't fix it like they did.  
The API is in the same directory as Stardew Valley.exe.
I believe I have the most up to date version of the game (1.15.4.0) and SMAPI (1.15.4)
I tried running it as an administrator.
I tried uninstalling and reinstalling SMAPI.
I tried rebooting my computer since I installed SMAPI.
I made sure I didn't extract the SMAPI installation files directly into the Stardew directory...

I don't know what's gone wrong.  Can someone please help? 

![same directory](https://user-images.githubusercontent.com/7054712/31106694-f985c3c4-a7b2-11e7-9bd1-bdb0298c6063.png)

![unhandled exception](https://user-images.githubusercontent.com/7054712/31106700-01b4f3b2-a7b3-11e7-8263-27143f2f261a.jpg)

**Comment by Pathoschild** [comment]
@GirlGalvanized The `StardewModdingAPI.AssemblyRewriters.dll` file is missing from your game folder, possibly because your antivirus removed it. See _[FAQs: SMAPI files disappear or your antivirus complains](https://stardewvalleywiki.com/Modding:Player_FAQs#SMAPI_files_disappear_or_your_antivirus_complains)_ for more info.

If you still need help, feel free to ask in [the SMAPI support thread](http://community.playstarbound.com/threads/108375) or [#modding on Discurd](https://discordapp.com/invite/StardewValley). :)
