### ISSUE TITLE
Add option to hide the SMAPI console

### ISSUE THREAD

**Issue by M-AlNoaimi** [Pathoschild/SMAPI#366]
Not exactly sure if this was already made or not but here I go.

The console in my preference should be either removed or create a config to enable/disable it.

**Comment by Pathoschild** [comment]
The console window _is_ SMAPI, so unfortunately adding an option to hide it isn't really feasible.

**Comment by NyCodeGHG** [comment]
Wouldn't it be theoretically possible to run SMAPI in the background and create an icon in the system tray and make the console window hidden behind a command line option? 
Edit: It's just an idea, I have zero experience with .NET, I just know it's pretty easy in the rust world, Idk how difficult this would be here.

**Comment by pipedream420** [comment]
Not sure how similar SMAPI code is to [Baldur's Gate 3 Script Editor](https://github.com/Norbyte/bg3se) I figured I'd mention it since it is a modding API and has a console but everything runs in the background by default and you have to enable the console window in the config file if you want it to show. My whole point being that it does seem like it could be possible.

**Comment by Pathoschild** [comment]
@pipedream420 There are two main console differences between SMAPI and BG3SE:

* SMAPI launches Stardew Valley within its own process, whereas Baldur's Gate 3 loads BG3SE. That means BG3SE can just avoid creating a console window, but that's not an option for SMAPI which is fundamentally a console application (with the window created automatically before any SMAPI code runs).

* The SMAPI console is meant for players by default (unless you get the 'SMAPI for developers' version). That's the only place that shows whether your mods are loaded along with any errors, warnings, and update alerts. It's already filtered by default to hide technical logs that may not be relevant to players.

  There are also cases where you can't launch the game without seeing the console (e.g. the confirmation prompt after a hard game crash); hiding the console in those cases would make the game unlaunchable.

So we could link to unofficial methods to hide it (e.g. minimize to tray tools), but an official option to hide it wouldn't really make sense for SMAPI's design.

**Comment by darrenoc3** [comment]
Claiming that it doesn't really make sense for SMAPI's design doesn't stand up to scrutiny considering `--no-terminal` works the way the user expects on Linux and MacOS. There's dozens of discussions on Google Search over the years about folks wanting to hide the console so it's strange that you are so opposed to a similar solution for Windows using a log file. 

Full disclosure: I am saying this as a guy whose partner left the room in a flood of tears because she accidentally closed the console window and lost our entire day's progress, so I'm inherently biased. But there seems to have been many requests for this to be added over the years. If you're amenable I could probably raise a PR to add a command line flag for it myself.

**Comment by Pathoschild** [comment]
@darrenoc3 Sure! The approach used on Linux/macOS wouldn't work on Windows, but I'm open to a PR to add an explicit opt-in CLI argument.

**Comment by LordFransie** [comment]
Everyone wants someone else to do it, no one wants to do the work. This is a feature that we shouldn't need, if you want it added the project is open source and PRs are regularly reviewed.
