### ISSUE TITLE
Running the Installer Deleted my steamapps folder

### ISSUE THREAD

**Issue by feudalpig** [Pathoschild/SMAPI#377]
as the title says once ran the installer and it was done I was going to tell steam where to find the .exe file to run it modded but long and behold the Entire steamapps folder has been deleted and I cant play any of my games. wtf is going on. 
edit: I have to re download EVERY game

**Comment by Pathoschild** [comment]
Hi @feudalpig. That's strange and unfortunate, but most likely not caused by the SMAPI installer. The installer only deletes specific files and folders, I don't see any case where it would delete the entire steamapps folder. Maybe you have another program like an antivirus or game manager that misbehaved?
