### ISSUE TITLE
Content API Invalidation Issue

### ISSUE THREAD

**Issue by Sakorona** [Pathoschild/SMAPI#391]
TownInterior.xnb apparently cannot be invalidated by any mods, so it's not clearing static references?

**Comment by Pathoschild** [comment]
@JohnsonNicholas Can you attach a sample mod which reproduces the issue?

**Comment by Sakorona** [comment]
https://rd.nexusmods.com/stardewvalley/mods/1573 when loaded with XnbLoader (it's a fairly common statement actually on these mods now)

**Comment by Pathoschild** [comment]
Confirmed. Here's a sample mod which alternates `townInterior.xnb` between inverted and grayscale using cache invalidation once per second. It correctly inverts the color on first load, but the cache invalidation never happens.

* [TestContentMod.zip](https://github.com/Pathoschild/SMAPI/files/1504410/TestContentMod.zip)
* [source code](https://github.com/Pathoschild/SMAPI/files/1504411/TestContentMod.cs.txt)

**Comment by Pathoschild** [comment]
@JohnsonNicholas This seems to work normally in the upcoming SMAPI 2.2.

* I inverted `townInterior.xnb` and loaded it via XNB Loader, which worked fine:
  > ![](https://user-images.githubusercontent.com/230581/33246986-b55fbedc-d2e8-11e7-97ab-72b335628f0a.png)

* To eliminate confounding factors, I wrote a simple mod which inverts the `townInterior.xnb` colors using `IAssetLoader` or `IAssetEditor`, which worked fine:
  > ![](https://user-images.githubusercontent.com/230581/33246828-6d37902c-d2e7-11e7-88ea-f18fd12b1792.png)

  Cache invalidation also worked for `townInterior`:
  > [20:23:04 TRACE Test content mod] Requested cache invalidation for 'townInterior'.
  > [20:23:04 TRACE SMAPI] Invalidated 1 asset names: townInterior. Reloaded 0 core assets.

  Note that SMAPI doesn't automatically reload map tilesheets when they're invalidated from the cache, but that shouldn't affect XNB Loader since it loads overrides during `Entry` (before `townInteriors` is loaded).

Can you reproduce this issue yourself? If so, I'll send you a test build of SMAPI 2.2 to try.

**Comment by Sakorona** [comment]
That's odd, I couldn't. 

My repro steps:

1. Delete the content folder, drag over the clean one from my steam install
2. Enter a town interior

??? It's working now?

**Comment by Pathoschild** [comment]
@JohnsonNicholas Was that with SMAPI 2.1?

**Comment by Sakorona** [comment]
Yes. But oddly, it didn't work before. I wonder if force clearing my content folder fixed it.

**Comment by Pathoschild** [comment]
Thanks! I'll close this then.
