### ISSUE TITLE
Startup crash 2.5.4

### ISSUE THREAD

**Issue by siesta630** [Pathoschild/SMAPI#470]
tried reinstall base game with SMAPI 2.5.4 only

Log:
https://log.smapi.io/dJ3XXvVx

**Comment by DarkKinght85** [comment]
i have some issue anyone can help me pls
https://imgur.com/a/TTPLL

**Comment by Pathoschild** [comment]
@siesta630 Your .NET Framework installation seems to be broken or corrupted. Try uninstalling .NET Framework and reinstalling .NET Framework 4.5.

@DarkKinght85 SMAPI sees the game, but the `Stardew Valley.exe` is invalid. That happens with some pirated versions of the game which replace the game executable (which is entirely unnecessary since the game has no DRM anyway). You won't be able to use SMAPI with that version. I suggest buying the game or trying a different download.

If you need any other help, feel free to ask in [the support thread](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375) or [on Discord](https://stardewvalleywiki.com/Modding:Community). The GitHub issues are only used to track development tasks. :)
