### ISSUE TITLE
Starting Stardew Valley With SMAPI

### ISSUE THREAD

**Issue by MarkusPiirits** [Pathoschild/SMAPI#507]
I Start The Game With SMAPI Then It Says Old Version

**Comment by Pathoschild** [comment]
If you didn't opt in to the Stardew Valley 1.3 beta, make sure you install [SMAPI 2.5.5](https://smapi.io/). Otherwise make sure you're using the latest version of the game. If you still need help, you can [post in the support forum](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375/) or [ask on Discord](https://stardewvalleywiki.com/Modding:Community#Discord).
