### ISSUE TITLE
Wedding ring recipe still missing. 

### ISSUE THREAD

**Issue by Halestorm42** [Pathoschild/SMAPI#540]
I’m running the latest version of SMAPI and SDV. Since the update where you fixed it it is gone from the traveling cart, but I still dont have the recipe in my crafting menu.

**Comment by Halestorm42** [comment]
Disabling SMAPI and playing a day without it re-enabled the recipe.

**Comment by Pathoschild** [comment]
I can't reproduce this. If it still happens:
1. load your save and check the crafting screen;
2. [upload your SMAPI log](https://log.smapi.io/) and post the link here;
3. post a zip of [your save files](https://stardewvalleywiki.com/Saves).

**Comment by Halestorm42** [comment]
I checked the crafting screen, the recipe is still missing.

https://log.smapi.io/XzMMNjXJ

[Fredrik_135053746.zip](https://github.com/Pathoschild/SMAPI/files/2086434/Fredrik_135053746.zip)

**Comment by Pathoschild** [comment]
Thanks! I was able to track it down with your save file.

This happens due to something the game is doing. `Game1.craftingRecipes` is set to `"Data//CraftingRecipes"`, then `Stats` loads `"Data\\CraftingRecipes"` and removes the wedding ring. Both refer to the same asset, so this removes the wedding ring from `Game1.craftingRecipes` too. That doesn't cause issues in the base game because it doesn't normalise asset names (SMAPI does), so there are two copies of the data.

I [reported the issue in the bug thread](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375/page-136#post-3288824) with a proposed fix.

**Comment by Halestorm42** [comment]
Glad to help :)

**Comment by Pathoschild** [comment]
Still present in Stardew Valley 1.3.18. I added it to a [summary of requested bug fixes](https://community.playstarbound.com/threads/stardew-valley-multiplayer-beta-known-issues-fixes-2.145034/page-15#post-3289919).

**Comment by Pathoschild** [comment]
Fixed in Stardew Valley 1.3.19.
