### ISSUE TITLE
Can't load DLLs?

### ISSUE THREAD

**Issue by Brennan1612** [Pathoschild/SMAPI#591]
This is the error I am getting and my mods folder. (Sorry if this is the wrong place for this)

I tried to find the files it says are missing but I had no luck.

[Mods.zip](https://github.com/Pathoschild/SMAPI/files/2342004/Mods.zip)

[SMAPI] Found 7 mods with warnings:
[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.

[SMAPI]       - CJB Cheats Menu 1.18.1 because its DLL 'CJBCheatsMenu.dll' doesn't exist.
[SMAPI]       - CJB Item Spawner 1.11.1 because its DLL 'CJBItemSpawner.dll' doesn't exist.
[SMAPI]       - CJB Show Item Sell Price 1.9.1 because its DLL 'CJBShowItemSellPrice.dll' doesn't exist.
[SMAPI]       - Tractor Mod 4.6-beta because its DLL 'TractorMod.dll' doesn't exist.
[SMAPI]       - Ui-Info-Suite-master because it contains files, but none of them are manifest.json.

**Comment by Pathoschild** [comment]
@Brennan1612 You downloaded the source code for those mods, instead of their compiled releases. You can download them from their pages on Nexus Mods instead. (Registering an account there is free, just scroll down past the payment options.)

If you still need help, feel free to ask in [#modding on the Stardew Valley Discord](https://stardewvalleywiki.com/Modding:Community#Discord), in the [support forum thread](https://community.playstarbound.com/threads/108375), or on the [Nexus mod page](https://www.nexusmods.com/stardewvalley/mods/2400).

**Comment by Brennan1612** [comment]
oh, thanks a lot!

**Comment by Fluffeecheese** [comment]
Been trying to install the SVE mod but dll won't load

**Comment by Pathoschild** [comment]
@Fluffeecheese Hi! Come ask in [#using-mods on the Stardew Valley Discord](https://stardewvalleywiki.com/Modding:Community#Discord) and we'll help you get it working.
