### ISSUE TITLE
Newest version of Smapi won't install

### ISSUE THREAD

**Issue by Thatkid312** [Pathoschild/SMAPI#650]
Ok so I downloaded the newest version of SMAPI, 2.11.2, and the installer downloaded just fine. I unzipped the file just fine too. But when I try to download SMAPI with the installer, it won't work. It shows me an error and that's it. Is anyone else having this problem?

**Comment by Pathoschild** [comment]
The installer itself works fine, but we'll need to run some tests to see what the issue is on your computer. See [_ask for help_ in the troubleshooting guide](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Ask_for_help) for the best places to ask. (GitHub issues are only used for tracking development tasks, so most modders who could help won't see questions here.)
