### ISSUE TITLE
SMAPI uses "wrong" terminal - Linux

### ISSUE THREAD

**Issue by saltedcoffii** [Pathoschild/SMAPI#695]
When I run Stardew Valley, (I'm using Steam), SMAPI launches using my system's XTerm, the pre-installed terminal on the system. This terminal has small text and is hard to read. I have the standard GUI terminal for my system gnome-terminal, set up to use a OpenDyslexic, as it's easier for me to read. XTerm doesn't have that configuration option. Is there a way to make SMAPI use gnome-terminal as it's default terminal?

I am running Ubuntu 16.04 LTS, SMAPI 3.0.2, and Stardew Valley 1.4.4. Thank you :)

EDIT: I'd also like to tag this issue as a question but I can't figure out how to do that.

**Comment by Pathoschild** [comment]
@kingliamb SMAPI has a list of preferred terminals for compatibility, but you can override it:

1. Open the `StardewValley` file (the one with no extension) in a text editor.
2. Find the lines that look like this:
   ```sh
   # select terminal (prefer xterm for best compatibility, then known supported terminals)
   for terminal in xterm gnome-terminal kitty terminator xfce4-terminal konsole terminal termite alacritty mate-terminal x-terminal-emulator; do
   ```
3. Remove `xterm` from the list, and it'll prefer `gnome-terminal` instead.

**Comment by xrogaan** [comment]
Alternatively, xterm could go at the end of that list. xterm is most likely installed everywhere, but other emulators are most likely primarily used by people. Thus, xterm should be used as last resort.

**Comment by Pathoschild** [comment]
Terminal order is a perennial topic for the Linux version. A player will report that terminal Y works but X doesn't, so we'll shift the order; then another will report that Y fails for them while X works.

The main problem is that the launcher can't tell whether a terminal is compatible ahead of time; if it isn't, the terminal just won't launch or .NET will crash. `xterm` is the one that works consistently across all distros when it's installed, which is why it's the default preferred terminal. In most cases SMAPI being functional is more important than having it use the default terminal.

We can certainly discuss whether we should rethink the SMAPI terminal entirely, though that'd be its own discussion.

**Comment by littlek3000** [comment]
This is still an issue 5 years later.

**Comment by Pathoschild** [comment]
I think my previous comments still apply too.

**Comment by Juicysteak117** [comment]
For what it's worth, I ran across this same issue of too small text just now as well on my partner's system (Mint). I followed your previous comment @Pathoschild to opt for `gnome-terminal` which results in no terminal showing nor mention of error in the `SMAPI-Latest.txt` log file. Not sure if this should be opened as a separate issue or not because I'm not sure if the errors are just being echoed elsewhere, but the wiki has been unhelpful unfortunately.

**Comment by Squaredude** [comment]
After some troubleshooting of the `StardewValley` bash file, I'm not sure what's going on, but I arrived at a workaround. I'm on KDE, so I'm using the Konsole terminal.

At the beginning of the file there's 3 variables for the user to modify:

```
# Whether to avoid opening a separate terminal window, and avoid logging anything to the console.
# This isn't recommended since you won't see errors, warnings, and update alerts.
SKIP_TERMINAL=false

# Whether to avoid opening a separate terminal, but still send the usual log output to the console.
USE_CURRENT_SHELL=false

# Specify terminal name to open and output logs
PREFER_TERMINAL_NAME=""
```

The relevant one for the workaround will be `USE_CURRENT_SHELL`.

1. Edit the file so that `USE_CURRENT_SHELL=true`.

2. Create an alias in your `~/.bash_aliases` file: `alias run_stardew="/path/to/SteamLibrary/steamapps/common/Stardew\ Valley/StardewValley"`

3. Reload / reopen your terminal, and run `run_stardew`.

4. The game should now launch and the output will be in the open terminal, with the proper formatting and all.

Running it this way will make it count as running in Steam (I run games with Steam open, haven't tried running the command with Steam closed).

Unfortunately, running it from Steam, with `--prefer-terminal-name=konsole` or editing `PREFER_TERMINAL_NAME="konsole"` in `StardewValley` will end up as @Juicysteak117 mentions, with the game launching without a terminal.

**Comment by KWottrich** [comment]
The issue with using anything except xterm when running the game as a Steam game comes down to the fact that the Linux version of Stardew Valley uses the [Steam Linux Runtime 1.0 (Scout)](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/container-runtime.md#steam-linux-runtime-10-scout). The Scout runtime replaces the `/usr` folder, which is where most terminals get installed (in places like `/usr/bin`).

When the StardewValley script runs, it is executing from within the runtime. When it goes about picking the first terminal it finds among the list provided, it will only find xterm because that's the only thing installed in the runtime. The only way around this is to run the StardewValley startup script outside of Steam (such as by running it from a standard terminal or file manager) or to figure out how to make your preferred terminal available from within the runtime. The latter would be complicated because the runtime _wants_ to isolate system libraries and binaries -- that's the whole point of the runtime.
