### ISSUE TITLE
Game crashes when I launch through anything other that vanilla, and changing resolution after first launch

### ISSUE THREAD

**Issue by MisterLahey** [Pathoschild/SMAPI#714]
**Describe the bug**
When I first launch the game using Smapi or Mod Drop, the game launches fine. But when I got to change resolution the game crashes immediately. Upon launching next time, I get a white screen. Even after deleting preferences still yields a white screen and not responding.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Launch Game
2. Console and everything loads fine
3. Game goes whitescreen and does not respond
4. If  the game launches I go to change resolution using Alt+Enter
5. Total Crash.

Already disabled Riva Tuner, Added the entire folder to Malwarebytes exclusion zone, and Disabled Afterburner. Already Reinstalled .NET Framework 4.5.2 and XNA Framework 4.0.

Launch through Steam or Mod Drop - crash
Launch with SMAPI - fine
Launch with SMAPI and change resolution - crash
Launch vanilla game - fine
Launch vanilla and change resolution - fine
Delete Preferences and launch with Steam, Mod Drop, or SMAPI - Crash

**Log file**
https://smapi.io/log/f29188142be44430a00c802eea75812f

**Screenshots**
Launch Pref's "C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\StardewModdingAPI.exe" %command%

this is after I launch, after recovering from this crash log.

https://gyazo.com/dd9d7749131b76c70603a9c56c7b1931

**Comment by Pathoschild** [comment]
That's a game bug which happens when the game window is resized mid-draw.

Some software (e.g. RivaTuner, AfterBurner, GeForce Xtreme, etc) can resize the game window many times within a couple of seconds, which often causes the crash. The issue can be SMAPI-specific due to that software applying different settings (since it may see SMAPI and vanilla Stardew Valley as two different programs).

I sent you a custom build of the game with the bug fixed per our discussion on Discord, and I'll let the game developers know so it'll hopefully be fixed in the next game update.
