### ISSUE TITLE
[Feature Request] Add a command for auto-generating a smapi.io/log from within the cmd prompt

### ISSUE THREAD

**Issue by Zefferis** [Pathoschild/SMAPI#746]
[OS: Windows]

Since SMAPI should already have access to:
``"C:\Users\<USER>\AppData\Roaming\StardewValley\ErrorLogs\SMAPI-latest.txt"``

I think it would be nice if it could paste and parse that into the actual webpage smapi.io/logs after a command like ``make_log``

Either
1. Add the saved SMAPI log URL to the clipboard after it's particular command is used or
2. Open the users default browser and open to the newly generated smapi.io/log

**Comment by Pathoschild** [comment]
Thanks for the suggestion! Pull requests are welcome if you want to tackle this, or it could be added to mod managers like ModDrop or Vortex. I don't have any specific plans to implement this though, so I'll close this ticket since GitHub issues aren't really the place to track long-term suggestions/ideas.
