### ISSUE TITLE
Crash when using arrow keys in console

### ISSUE THREAD

**Issue by MaienM** [Pathoschild/SMAPI#758]
**Describe the bug**
Pressing up in the console causes the game to crash... sometimes.

**To Reproduce**
I've managed to reproduce it a few times with the following steps, but not consistently. Loading a save might not actually be needed, not sure.

1. Load any save.
0. Switch to the console and press 'up'.
0. Game crashes.

**Log file**
https://smapi.io/log/0e5084e5ff7e4ae6a4331566d9dcebf0

**Screenshots**
N/A

**Comment by Pathoschild** [comment]
Hi! That seems to be a bug in the underlying .NET Framework or the Linux drivers. I'll close this ticket since it's not a SMAPI issue, but if you ping me in [#using-mods on the Stardew Valley Discord](https://smapi.io/community#Discord), we could run some tests to see if I can add a workaround for the issue in an upcoming update.
