### ISSUE TITLE
Strip file paths from uploaded smapi.io logs

### ISSUE THREAD

**Issue by rhoot** [Pathoschild/SMAPI#762]
When you upload a log file to smapi.io, not only does that file contain the file path of where the game is installed, the public log page will put that info in a very prominent info box at the top. The problem with that is: The path may contain personal information, as is almost always the case with game install paths on Linux (it typically contains the user's name).

Since the install path should be mostly irrelevant anyway it may be prudent to just not include it on the parsed log page.

**Comment by Pathoschild** [comment]
The install path is often needed in troubleshooting, so we can't remove it without making user support much harder.

SMAPI could detect when it's running under the current user's home directory, and replace the home directory with `~/` in the log. That's a somewhat bigger task though, since we'll need to do it for error messages which include a file path too (e.g. invalid JSON, missing file, etc). That might also make errors more confusing for players, especially on MacOS where they might not know what `~` means.

I think the privacy issue is somewhat mitigated because the page isn't accessible to anyone unless the uploader explicitly sends them a URL, and it disappears entirely after a month (unlike posting the log file itself in a Discord channel or forum post which is permanent).

**Comment by Pathoschild** [comment]
Pull requests are welcome if someone wants to suggest changes for this, but I don't have any plans to implement this ticket specifically. I'll close this ticket since GitHub issues aren't really the place to track long-term suggestions/ideas.
