### ISSUE TITLE
Out of memory exceptions

### ISSUE THREAD

**Issue by zwei7** [Pathoschild/SMAPI#780]
**Describe the bug**
SMAPI reports System.OutOfMemoryException

**To Reproduce**
Use 365 mods (2 out-of-date on purpose, not beta testing, 1 didn't update) running SMAPI 3.10.
Start hosting a new multiplayer game with only 1 person playing.
Play for 3-4 in game days straight.
During those days I would be fishing mostly.

About 75% of the way down the log during a save at the end of day 2 it reports the 1st instance of system out of memory. Then I check on Taskmanager and it flushes it out. On launch taskmanager reports SMAPI Stardew using 2.0 gigs, then 2.7 gigs on loading a game. Then 1.3 gigs during the day 2 save error. Then when trying to save day 3 it hangs at the save screen is stuck. The game runs, but no saving, this is when it reports the 2nd out of memory exception.

**Log file**
https://smapi.io/log/58d445218f5a413f8fe3241b7ac47096

**Comment by Nattywwc** [comment]
Stardew Valley can only handle so many mods before the memory starts to give problems during the saving loop.
That's why SMAPI recently introduced the x64 support (in 3.10), but you have to also run x64 which takes a bit of work.
Give it a read here: https://stardewvalleywiki.com/Modding:Migrate_to_64-bit_on_Windows

**Comment by Pathoschild** [comment]
Hi! GitHub issues are only used to track specific development tasks. If Nattywwc's link doesn't help, see [Modding:Help](https://stardewvalleywiki.com/Modding:Help) on the wiki for the best places to ask for help.
