### ISSUE TITLE
Renamed Log Files are Deleted on Game Start

### ISSUE THREAD

**Issue by Smugger21** [Pathoschild/SMAPI#796]
Renaming "SMAPI-latest.txt" to any other name and then starting up the game will delete everything in the folder and make a new "SMAPI-latest.txt" file. Does not allow you to keep old log files in the ErrorLogs file folder.

**To Reproduce**
Stated above

**Comment by Pathoschild** [comment]
Hi! That's by design. Both SMAPI and the game can create extra log files for a session (e.g. to support split-screen), and players were often confused about which file to upload (or worse would just upload the wrong one). So the current behavior is that starting a new session will automatically clear any previous logs, so that it's easy to know which are relevant when reporting an error. If you want to keep older log files, you can move them into a different folder to do it.
