### ISSUE TITLE
[SMAPI 3.13.4/3.14.0] Rapid Stuttering

### ISSUE THREAD

**Issue by VaelophisNyx** [Pathoschild/SMAPI#843]
**Describe the bug**
For some reason the Client Bounds get redrawn every few dozen frames, causing the whole game to stutter quite hard. This has started to occur for seemingly no reason, after flawless function for the past two weeks or so, and 4-7 hours per session. Log entry in question is frequent repeats of `[19:28:03 TRACE game] Window_ClientSizeChanged(); Window.ClientBounds={X:8 Y:31 Width:2498 Height:1417}`. Changing from Windowed to Borderless did not fix this. This is also unrelated to VSync.

**To Reproduce**
Reproduction method unclear.

**Log file**
https://smapi.io/log/42c3aee93f6e4ceba3ad85e4c6f4afdd

**Comment by VaelophisNyx** [comment]
Additonal information: This persists after a close & relaunch of the game. No new mods had been added at the time this bug started to occur. No settings had been tweaked either.

While stuttering, the game is using only 2% of available CPU capacity, and about 1.2Gb of RAM out of ~30Gb available. Framerate was also excellent, stutters aside. Entirely unsure why this is happening, but it's made the game borderline unplayable
I am about to test on a new save, after checking if it still occurs in True Fullscreen mode.

Testing results for Fullscreen: It did indeed still stutter.
Testing for new save: Stutter not present
Note: Stutter is not present at the main menu.

What I gather is this means something is broken with either my save file, or that and a combo of mods & leftover data from long-removed mods

Side note, I was unaware of the update to 3.14 being available, and will give that a try as well
Stutter still present on 3.14

**Comment by Pathoschild** [comment]
Hi! Here's a few things you can try;
* Repeating errors (like the Json Assets errors in your log) can cause performance issues, so you should fix those first.
* If it still happens after fixing the errors, try [the suggested performance fixes](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Game_lags_or_stutters_in-game) in the troubleshooting guide.
* There's also some ongoing performance fixes in the recent SMAPI and Content Patcher updates that should help with stuttering.

I'll close this ticket since it's not a specific dev task, but if it still happens after trying those fixes, you can come ask in [#using-mods-help on the Stardew Valley Discord](https://smapi.io/community#Discord) and we'll invite you to the performance-testing thread there. That'll let you test the latest alpha builds meant to improve performance, and help track down any other performance issues in your case.
