### ISSUE TITLE
Trouble launching SMAPI 3.14.7 on steam deck

### ISSUE THREAD

**Issue by detrout** [Pathoschild/SMAPI#850]
Hello,

My friend was trying launch SMAPI 3.14.7 on a steam deck, and it wasn't working.

I tried running the modified StardewValley script installed by SMAPI from the terminal, with the extra modification that I deleted xterm from the list of terminals, because the steam deck doesn't have xterm installed by default.

The script reported errors being unable to find libhostfxr.so and after I copied that out of SMAPI 3.14.7 installer/internal/linux it also complained about not finding libhostpolicy.so.

With those two libraries copied into the StardewValley game directory I then had an error "Could not resolve CoreCLR path".

I worked around the problem by installing SMAPI 3.14.6, which seemed to have all required dependencies, but thought this issue probably needed to be reported.

As for the part of the script that looks for terminals maybe add a test to see if the terminal command is available?

maybe something like  (working from memory)

```bash
for terminal in xterm gnome-terminal; do
  if [ $(which $terminal) ]; then
     echo $terminal ;   # whatever the real command is
  fi
done
```

Hope this helps.

**Comment by Pathoschild** [comment]
Hi! It sounds like you're running the Proton version of the game with the Linux version of SMAPI. I just created [_Installing SMAPI on Steam Deck_](https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Steam_Deck) to cover the instructions for Steam Deck (including with Proton).

I'll close this ticket since it's not a dev task, but if you still need help feel free to ask in [#using-mods-help on the Stardew Valley Discord](https://smapi.io/community#Discord) and we'll help get it working. (You can ping me there with `@Pathoschild#0001` if you don't get an answer.)

**Comment by detrout** [comment]
Thank you!

And I really wish valve made it easier to tell if the steam deck is using the Linux or windows version of the game
