### ISSUE TITLE
SMAPI can not connect when I am playing multiplayer games over openvpn

### ISSUE THREAD

**Issue by Senkoi** [Pathoschild/SMAPI#877]
I used to play Stardew Valley with friends on openvpn. My Friend is host and I am farmhands.
  But I've found that when the host turns on SMAPI, I can't connect the way I did before (whether I turn on SMAPI or not) .
  When the host shuts down SMAPI, I can connect to it (whether I turn on SMAPI or not) .
Then, after trying, I found that by sending the byte 0x880000000 to a host without SMAPI turned on via openvpn, I was able to receive the string"StardewValley".
  Conversely, if the host turns on SMAPI, I receive nothing.

This is the instruction I use to send the data，10.8.0.10 is the host。
`echo -ne '\x88\x00\x00\x00\x00' | nc -unv 10.8.0.10 24642`

**Comment by Pathoschild** [comment]
Hi! See [_Can't connect to another player in multiplayer_](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Can.27t_connect_to_another_player_in_multiplayer) in the troubleshooting guide for some common fixes. I'll close this since I only use GitHub issues to track specific development tasks; if the suggested fixes don't work for you, come [ask in one of the recommended places](https://stardewvalleywiki.com/Modding:Help), and we'll  help get it working.
