### ISSUE TITLE
(Windows Only Issue) Launching with SMAPI ignores my DualShock 4 Custom Config in Steam.

### ISSUE THREAD

**Issue by CyberRacc** [Pathoschild/SMAPI#880]
**Describe the bug**
Windows 11 only, problem does not occur on Linux, I play on both my main PC (Windows 11) and my Laptop (Manjaro Linux).
I use Steam Input to configure my DualShock 4 controller, which works perfectly on the base game and on Linux with SMAPI, but not Windows with SMAPI. The game pretty much ignores my custom config when using SMAPI on Windows, always using the default controls instead which is not usable for me as I constantly change between playing on PC and on Switch so I need the config to work for consistency.

Yes I am launching through Steam with "StardewModdingAPI %command%" in the launch options, I am not using any external input application, DS4 Windows is the only one I use and it is closed.

**To Reproduce**
1. Set custom configuration in Steam Input for DualShock 4, swap cross & circle, set share to screenshot, left touchpad to tasks, right touchpad to map.
2. Start game, verify that the config is loaded, it is.
3. Share still opens tasks, left touchpad does nothing, Cross and Circle are not swapped.

**Log file**
https://smapi.io/log/d8b794fea909444d8272639f2d371f01

**Screenshots**
![grafik](https://user-images.githubusercontent.com/89751580/196256362-6058451b-8054-4dfc-ae8f-dfec0915d546.png)

My controller configuration in Steam, works only without SMAPI on WIndows, works with or without SMAPI on Linux. No idea what is happening.

**Comment by Pathoschild** [comment]
Hi! It seems Steam Input doesn't always handle multiple game windows correctly. Unfortunately that seems to be a limitation of Steam Input rather than an issue with SMAPI itself, and we haven't figured out why it works for some players but not others yet.

 See [_SMAPI doesn't recognize controller (Steam only)_](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#SMAPI_doesn.27t_recognize_controller_.28Steam_only.29) in the troubleshooting guide for some suggested fixes. You already tried most of them, so there's just the last resort of using a third-party controller app left.

I'll close this ticket since it's not a specific development task for SMAPI itself, but feel free to join [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) if you'd like to discuss further. I'd love to find a solution or more info, since it affects a subset of other players too.
