### ISSUE TITLE
Add custom language made the translation of item scythe from `Scythe` to `3`

### ISSUE THREAD

**Issue by avxit** [Pathoschild/SMAPI#894]
**Describe the bug**

Add custom language made the translation of item scythe from `Scythe` to `3`

**To Reproduce**

*SMAPI `v3.18.1` & Content Patcher `1.28.4`*

1. Create a Content Patcher Mod to add a custom language

```json
{
  "Format": "1.28.0",
  "Changes": [
    {
      "Action": "EditData",
      "Target": "Data/AdditionalLanguages",
      "Entries": {
        "Avx.VietnameseTranslation": {
          "ID": "Avx.VietnameseTranslation",
          "LanguageCode": "vi",
          "ButtonTexture": "Mods/Avx.VietnameseTranslation/Button",
          "UseLatinFont": true,
          "FontPixelZoom": 1,
          "TimeFormat": "[HOURS_24_00]:[MINUTES]",
          "ClockTimeFormat": "[HOURS_24_00]:[MINUTES]",
          "ClockDateFormat": "[DAY_OF_WEEK] [DAY_OF_MONTH]"
        }
      }
    },
    {
      "Action": "Load",
      "Target": "Mods/Avx.VietnameseTranslation/Button",
      "FromFile": "assets/LanguageButton.png"
    }
  ]
}
```

2. Start the game and you will see the change

**Log file**

**Screenshots**

![image](https://user-images.githubusercontent.com/38064714/212141098-c8c54a9d-9057-4f6e-8ef0-e3dad52b54bc.png)

**Comment by Pathoschild** [comment]
In Stardew Valley 1.5.6 and earlier, items have an extra field in non-English data for the translated display name. So when you add a custom language, you'll also need to add the display name fields.

I'll close this since it's not related to SMAPI, but see [Modding:Items](https://stardewvalleywiki.com/Modding:Items) for info on the format and feel free to ask questions in [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord). (If you don't get an answer, you can ping me there with `@Pathoschild#0001`.)
