### ISSUE TITLE
Unable to open the game when launching with steam on macOS ventura

### ISSUE THREAD

**Issue by haiming12138** [Pathoschild/SMAPI#898]
Since updating to macOS venture, SMAPI won't open the game properly if launching with steam. If I tried to launch with steam this message will pop up.
<img width="897" alt="Screenshot 2023-01-27 at 9 14 43 PM" src="https://user-images.githubusercontent.com/102835461/215237161-cce0ee99-393d-4420-952b-bc081a55456d.png">

The only way for me to launch the game is by running the executable manually in the terminal, which is a minor inconvenient.

**Comment by Pathoschild** [comment]
Hi! I'll close this since it's not a specific development task, but can you come ask in [#using-mods-help on the Stardew Valley Discord](https://smapi.io/community#Discord) so we can run some tests? There are some macOS users there who can help, and I think sure some of them use macOS Ventura. If you don't get an answer, you can ping me there with `@Pathoschild#0001`.
