### ISSUE TITLE
Arm64 support with native mono

### ISSUE THREAD

**Issue by neofeo** [Pathoschild/SMAPI#903]
Hi folks, we have had SV working  on cheap arm64 handhelda since long time ago. I grabbed a copy with steam SV 1.5.6 and works just fine with arm64 mono.

The only thing we lack is mods bc of this api. Could be possible  an arm64 release?

Have a nice day.

![20230428_235548](https://user-images.githubusercontent.com/84641119/235286620-01ecb42a-6b6f-4337-9f9c-8eb2da1aeb8d.jpg)

**Comment by anonymus177** [comment]
Sorry if I'm talking nonsense, I really have only a very superficial knowledge of programming but as far as I'm aware SMAPI for Android should run on arm64, right? It is in the process of being updated to 1.5.6 right now. 

Although I have no idea how well would it run with the Steam release, or even whether at all.

**Comment by neofeo** [comment]
Hi, I am referring to ARM64 Linux with mono. It's  the desktop game,not the android one.

**Comment by anonymus177** [comment]
I understood that correctly and was pointing out that Android is the only version running on the same architecture, and since Android is Linux-based, my idea was trying the SMAPI for Android with the Steam release files. Sorry If I'm not 100 % clear, English is not my first language.

**Comment by neofeo** [comment]
I dont  think that would  work at all. But even then, I would like a basic explanation on how to build this since there are no instructions for doing so.

**Comment by Pathoschild** [comment]
Hi! The [technical docs](https://github.com/Pathoschild/SMAPI/blob/develop/docs/technical/smapi.md) explain how to build and package SMAPI, and anyone is welcome to port releases to other platforms if they want. I'm also happy to discuss changes to better support ARM64 if needed.

I'll close this ticket since I don't track suggestions as GitHub issues, but feel free to comment on [issue #632](https://github.com/Pathoschild/SMAPI/issues/632) to discuss ARM64. You can also come join [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) to discuss with mod authors more widely (since most authors don't watch these issues).
