### ISSUE TITLE
Error starting saved save

### ISSUE THREAD

**Issue by vniciuspo** [Pathoschild/SMAPI#913]
Hello, when I open my save with the zenith farm, the game exit by itself and after a few hours it returns to normal, this is common, help me

**Comment by vniciuspo** [comment]
Note: Could using the Ridsidge Village mod have anything to do with this?

**Comment by Pathoschild** [comment]
Hi! That's probably an issue with one of your mods (rather than SMAPI itself). I'll close this since it's not a specific development task, but you can come ask in [#modded-game-support on the Stardew Valley Discord](https://smapi.io/community#Discord) and we'll help you find the cause. If you don't get an answer, feel free to ping me there with `@pathoschild`.
