### ISSUE TITLE
Create a "at your own risk" SMAPI 32 bit to support SDV 1.5.6

### ISSUE THREAD

**Issue by JeodC** [Pathoschild/SMAPI#927]
The last version of SMAPI to support legacy Stardew Valley is 2.11.3. This means that in order to use mods you must rollback your Stardew Valley game version to 1.3.36.

The compatibility branch is currently on 1.5.6. This branch is still widely used on 32 bit systems, especially Linux systems and Raspberry Pi. Unfortunately, Steam metrics won't show you this.

A group of developers behind PortMaster (https://portmaster.games/detail.html?name=stardewvalley) got Stardew Valley working on various retro handheld devices (Anbernic, Powkiddy, etc) by using the legacy version. I would like to propose that a version of SMAPI be released to support legacy 1.5.6, and be an "at your own risk" version--meaning it would be entirely unsupported issue-wise beyond ensuring it boots, and users would be on their own regarding finding which mods and which mod versions will work.

Thank you.

Edit: Here is an early video guide that will hopefully showcase how this works: https://www.youtube.com/watch?v=cWBM2_acOS8

And a written version of the video guide: https://retrogamecorps.com/2021/11/30/stardew-valley-on-retro-handhelds/

**Comment by garik816** [comment]
Has anyone gotten SMAPI to work on a retro console or raspberry pi?

**Comment by Pathoschild** [comment]
Hi! I don't have any plans to maintain an official version for the compatibility branch currently, since [there are significant unknowns with how it'd work](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Known_issues) and it's already a lot of work just to support the main version of the game.

Anyone is welcome to port SMAPI to the compatibility branch unofficially though (like we already do for Android), and I can help with any questions if someone wants to try it. That would be covered under the pinned [#632: SMAPI on other platforms](https://github.com/Pathoschild/SMAPI/issues/632) thread.

I'll close this thread, but feel free to discuss compatibility ports in #632!
