### ISSUE TITLE
A meadowlands farm cannot be created

### ISSUE THREAD

**Issue by Chris82111** [Pathoschild/SMAPI#957]
**Description**
A meadowlands farm cannot be created. The problem is the function `menu.createdNewCharacter(true);` or one that follows. An exception is thrown when a new meadowlands farm is created.
I think this is a general problem, but I am using a [multiplayer](https://github.com/Chris82111/SMAPIDedicatedServerMod/tree/develop) mod. For example, if I create a new farm with `Game1.whichFarm = 6;` for beach and call the function, a new world is created. This means that all the necessary settings have been made correctly.

**To Reproduce**
If a new farm is created with `Game1.whichFarm = 7;` for meadowlands and the function `menu.createdNewCharacter(true);` is called, an exception is thrown.

**Log file**
[SMAPI-latest.txt](https://smapi.io/log/e55c59da16f44322849e2830e0e7f62c)

**Error**
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Stardew Valley
  StackTrace:
   at StardewValley.Farm.onNewGame()
   at StardewValley.Game1.loadForNewGame(Boolean loadedGame)
   at StardewModdingAPI.Framework.SGame.loadForNewGame(Boolean loadedGame)
   at StardewValley.Menus.TitleMenu.createdNewCharacter(Boolean skipIntro)
   at DedicatedServer.HostAutomatorStages.StartFarmStage.Execute(Object sender, UpdateTickedEventArgs e) in C:\Users\Chris82111\Desktop\ded\SMAPIDedicatedServerMod\DedicatedServer\HostAutomatorStages\StartFarmStage.cs:line 301
```

**Comment by Pathoschild** [comment]
Hi! The meadowlands farm is implemented as [a custom farm type](https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.5.5#Custom_farm_types). Farm type 7 is `mod`, which requires the `Game1.whichModFarm` field to be set.

If you need help updating the mod to support it, you can come ask in [#making-mods-general on the Stardew Valley Discord](https://smapi.io/community#Discord). Most people who can help don't watch the SMAPI issues, since they're only for SMAPI development tasks. Feel free to ping me there if you don't get an answer!
