### ISSUE TITLE
SMAPI gets detected as malware on Mac (again)

### ISSUE THREAD

**Issue by cooperspencer** [Pathoschild/SMAPI#973]
Similar to this one: https://github.com/Pathoschild/SMAPI/issues/971
I installed SMAPI 1.4.9 last week and it worked perfectly fine, tried to start it today and then I got the malware message again
![image](https://github.com/user-attachments/assets/2798565a-1cbc-48bc-a684-eca71ea4b859)

**Comment by WillowMarmon** [comment]
Do we have any updates on this? None of my usual methods of bypassing this work at all. (including fully disabling the gatekeeper).

**Comment by SeregaSRG** [comment]
This is a very pressing problem. 
I haven't found any solutions either.

**Comment by gingerharlot** [comment]
https://www.reddit.com/r/SMAPI/comments/1h0fgv9/solution_for_mac_malware_issue_with_smapi_417/?rdt=40764

I followed the first instructions on this post and it did not work, but I installed the SMAPI 4.1.8-alpha as well as uninstalled and reinstalled Stardew Valley and I no longer received the malware pop up. Hopefully this will work for anyone else with this issue until it can be properly fixed. :)

**Comment by waterwaterrr** [comment]
I have the same problem here.

**Comment by Micro-ATP** [comment]
the same problem as

**Comment by LustyFarmer** [comment]
mine is similar, says this instead- “install on macOS.command” is damaged and can’t be opened. You should move it to the Trash.

been saying that since the most recent SDV game update, which we needed an updated smapi for so been trying to update since then with no success at all.

**Comment by IkoSong** [comment]
same problem.

**Comment by Pathoschild** [comment]
Hi! It seems something changed recently with the macOS security restrictions. If you're still having issues, following the updated [macOS install guide](https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Mac) should fix that. Make sure to follow each step carefully, since it may not work if you skip a step.

Note that these GitHub issues are only used to track technical work. For user support, please ask on the public mod pages instead or see [Modding:Help](https://stardewvalleywiki.com/Modding:Help) on the wiki.

**Comment by Svring** [comment]
for anyone who stepped upon this issue, in [install guide for mac](https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Mac) there is a section:

<img width="932" height="326" alt="Image" src="https://github.com/user-attachments/assets/7c0dae28-d5bf-408d-b269-77fa0eaee86f" />

following these steps should fix the problem.
